// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.


import 'trackAPI_test.dart' as trackAPI_test;
import 'user_test.dart' as user_test;


void main() {
  //fload_discography_test.main();
  trackAPI_test.main();
  user_test.main();
}
