// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'load_discography_test.dart' as load_discography_test;
import 'trackAPI_test.dart' as trackAPI_test;
import 'user_test.dart' as user_test;
import 'widget_test.dart' as widget_test;

void main() {
  //fload_discography_test.main();
  trackAPI_test.main();
  user_test.main();
  widget_test.main();
}
